name: pytask-markdown

channels:
  - conda-forge
  - nodefaults

dependencies:
  - pip
  - setuptools_scm
  - toml

  # Package dependencies
  - pytask >= 0.3
  - pybaum >=0.1.1

  # Misc
  - pdbpp
  - black
  - jupyterlab
  - matplotlib
  - pre-commit
  - pytest
  - pytest-cov
  - tox

  - pip:
    - e .
